services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: securepassword
      MYSQL_DATABASE: tanamanku_massive_project
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - 3306:3306 # Optional: expose for external debugging

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: securepassword
      DB_NAME: tanamanku_massive_project
    ports:
      - 5000:5000 # Backend app exposed here
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - 3000:80 # Expose frontend on port 3000
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  mysql-data: # Persistent volume for MySQL data

networks:
  app-network: # Shared network for all services
    driver: bridge
